---
title: "Sun2 overexpression bulk RNA-seq analysis"
author: "Jian Zhang (zhang.jian@yale.edu)"
date: "`r format(Sys.Date())`"
output: 
  html_notebook: 
    code_folding: hide
  github_document: default
---


Using *Tophat2* and *Cuffdiff* to do reads mapping, gene quantification and DEGs identification.

Run the scripts in Yale linux server.

`perl 1.run.tophat2.parallel.pl /home/zj76/project/Xiao_Sun2_ad2/Sample_XH_1916_to_Sample_XH_1924`

`perl 2.run.cuffdiff.with.slurm.pl /home/zj76/project/database/mm10/Mus_musculus.GRCm38.96.gtf XH_19_16_17_18,XH_19_19_20_21,XH_19_22_23_24`

`sbatch cuffdiff.sh.run.slurm.sh`

```{r}
plot(cars)
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.
