library("limma")
library("locfit")
library("edgeR")
x <- read.delim(file="/home/gao/EDGER/mstrge/nonlnc_count.txt",header=T)
group <- factor(c('aN','aN','aN','bL','bL','bL','bL','cM','cM','cM','cM','dH','dH','dH','dH'))
y <- DGEList(counts=x[,2:16],group=group,gene=x[,1])
y <- calcNormFactors(y) #####TMM  normalize
dim(y)
plotMDS(y)
design <- model.matrix(~group)
y <- estimateGLMCommonDisp(y,design)
y <- estimateGLMTrendedDisp(y,design)
y <- estimateGLMTagwiseDisp(y,design,prior.df=5)
fit <- glmFit(y,design)
lrt.LvsN <- glmLRT(fit,coef=2)
topTags(lrt.LvsN)
lrt.MvsN <- glmLRT(fit,coef=3)
topTags(lrt.MvsN)
lrt.HvsN <- glmLRT(fit,coef=4)
topTags(lrt.HvsN)
lrt.HvsL <- glmLRT(fit,contrast=c(0,-1,0,1))
topTags(lrt.HvsL)
lrt.HvsM <- glmLRT(fit,contrast=c(0,0,-1,1))
topTags(lrt.HvsM)
lrt.MvsL <- glmLRT(fit,contrast=c(0,-1,1,0))
topTags(lrt.MvsL)
LN <- topTags(lrt.LvsN,n=Inf,sort.by="PValue")
write.table(LN,file="/home/gao/glmedger/NLNC_LN_edgeR_DET.txt",quote=F,sep="\t")
MN <- topTags(lrt.MvsN,n=Inf,sort.by="PValue")
write.table(MN,file="/home/gao/glmedger/NLNC_MN_edgeR_DET.txt",quote=F,sep="\t")
HN <- topTags(lrt.HvsN,n=Inf,sort.by="PValue")
write.table(HN,file="/home/gao/glmedger/NLNC_HN_edgeR_DET.txt",quote=F,sep="\t")
HL <- topTags(lrt.HvsL,n=Inf,sort.by="PValue")
write.table(HL,file="/home/gao/glmedger/NLNC_HL_edgeR_DET.txt",quote=F,sep="\t")
HM <- topTags(lrt.HvsM,n=Inf,sort.by="PValue")
write.table(HM,file="/home/gao/glmedger/NLNC_HM_edgeR_DET.txt",quote=F,sep="\t")
ML <- topTags(lrt.MvsL,n=Inf,sort.by="PValue")
write.table(ML,file="/home/gao/glmedger/NLNC_ML_edgeR_DET.txt",quote=F,sep="\t")
